---
- health: yellow
  status: open
  index: translation-uz
  pri: '5'
  rep: '1'
  docs.count: '0'
  docs.deleted: '0'
  store.size: 575b
  pri.store.size: 575b
- health: yellow
  status: open
  index: translation-sv
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.1mb
  pri.store.size: 4.1mb
- health: yellow
  status: open
  index: translation-tr
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.8mb
  pri.store.size: 3.8mb
- health: yellow
  status: open
  index: translation-ha
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.7mb
  pri.store.size: 3.7mb
- health: yellow
  status: open
  index: translation-ms
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.4mb
  pri.store.size: 4.4mb
- health: yellow
  status: open
  index: translation-tt
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 6mb
  pri.store.size: 6mb
- health: yellow
  status: open
  index: translation-pl
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.7mb
  pri.store.size: 3.7mb
- health: yellow
  status: open
  index: translation-ar
  pri: '5'
  rep: '1'
  docs.count: '0'
  docs.deleted: '0'
  store.size: 575b
  pri.store.size: 575b
- health: yellow
  status: open
  index: translation-id
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.8mb
  pri.store.size: 3.8mb
- health: yellow
  status: open
  index: translation-fa
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.5mb
  pri.store.size: 4.5mb
- health: yellow
  status: open
  index: translation-zh
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.3mb
  pri.store.size: 3.3mb
- health: yellow
  status: open
  index: translation-sq
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.9mb
  pri.store.size: 3.9mb
- health: yellow
  status: open
  index: translation-de
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.9mb
  pri.store.size: 3.9mb
- health: yellow
  status: open
  index: translation-ru
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.4mb
  pri.store.size: 4.4mb
- health: yellow
  status: open
  index: transliteration
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 2.8mb
  pri.store.size: 2.8mb
- health: yellow
  status: open
  index: translation-sw
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.2mb
  pri.store.size: 3.2mb
- health: yellow
  status: open
  index: translation-bn
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 5.1mb
  pri.store.size: 5.1mb
- health: yellow
  status: open
  index: translation-ko
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.2mb
  pri.store.size: 4.2mb
- health: yellow
  status: open
  index: translation-ml
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 7.9mb
  pri.store.size: 7.9mb
- health: yellow
  status: open
  index: translation-ur
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.4mb
  pri.store.size: 4.4mb
- health: yellow
  status: open
  index: translation-fr
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.7mb
  pri.store.size: 3.7mb
- health: yellow
  status: open
  index: translation-ta
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 8mb
  pri.store.size: 8mb
- health: yellow
  status: open
  index: translation-it
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.4mb
  pri.store.size: 3.4mb
- health: yellow
  status: open
  index: translation-fi
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.1mb
  pri.store.size: 4.1mb
- health: yellow
  status: open
  index: translation-ja
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 5.7mb
  pri.store.size: 5.7mb
- health: yellow
  status: open
  index: translation
  pri: '5'
  rep: '1'
  docs.count: '12472'
  docs.deleted: '0'
  store.size: 13.6mb
  pri.store.size: 13.6mb
- health: yellow
  status: open
  index: translation-ro
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.4mb
  pri.store.size: 3.4mb
- health: yellow
  status: open
  index: translation-mrn
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.6mb
  pri.store.size: 3.6mb
- health: yellow
  status: open
  index: translation-bs
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.4mb
  pri.store.size: 3.4mb
- health: yellow
  status: open
  index: translation-cs
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.8mb
  pri.store.size: 3.8mb
- health: yellow
  status: open
  index: translation-so
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.5mb
  pri.store.size: 3.5mb
- health: yellow
  status: open
  index: translation-no
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.1mb
  pri.store.size: 3.1mb
- health: yellow
  status: open
  index: translation-nl
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.7mb
  pri.store.size: 3.7mb
- health: yellow
  status: open
  index: translation-es
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.4mb
  pri.store.size: 3.4mb
- health: yellow
  status: open
  index: tafsir
  pri: '5'
  rep: '1'
  docs.count: '18708'
  docs.deleted: '0'
  store.size: 215.4mb
  pri.store.size: 215.4mb
- health: yellow
  status: open
  index: text-font
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 10.5mb
  pri.store.size: 10.5mb
- health: yellow
  status: open
  index: translation-en
  pri: '5'
  rep: '1'
  docs.count: '37416'
  docs.deleted: '0'
  store.size: 19.4mb
  pri.store.size: 19.4mb
- health: yellow
  status: open
  index: translation-th
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 8.1mb
  pri.store.size: 8.1mb
- health: yellow
  status: open
  index: translation-az
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 4.9mb
  pri.store.size: 4.9mb
- health: yellow
  status: open
  index: translation-pt
  pri: '5'
  rep: '1'
  docs.count: '6236'
  docs.deleted: '0'
  store.size: 3.8mb
  pri.store.size: 3.8mb
